#!/usr/bin/env python3.6
from __future__ import print_function, with_statement

import os
import re
import shutil
import subprocess
import sys
import tempfile

# don't fill in both of these
select_codes = []
ignore_codes = ["E121", "E122", "E123", "E124", "E125",
                "E126", "E127", "E128", "E129", "E131", "E501"]
# Add things like "--max-line-length=120" below
overrides = ["--max-line-length=120"]


def system(*args, **kwargs):
    kwargs.setdefault('stdout', subprocess.PIPE)
    proc = subprocess.Popen(args, **kwargs)
    out, _err = proc.communicate()
    return out


def autopep8(filepath):
    args = ['autopep8', '--in-place']
    if select_codes and ignore_codes:
        print(u'Error: select and ignore codes are mutually exclusive')
        sys.exit(1)
    elif select_codes:
        args.extend(('--select', ','.join(select_codes)))
    elif ignore_codes:
        args.extend(('--ignore', ','.join(ignore_codes)))
    args.extend(overrides)
    args.append(filepath)
    _output = system(*args)


def main():
    try:
        import autopep8 as ap8
    except ImportError:
        print("'autopep8' is required. Please install with `pip install autopep8`.", file=sys.stderr)
        exit(1)

    modified = re.compile(r'^[AM]+\s+(?P<name>.*\.py)', re.MULTILINE)
    basedir = system('git', 'rev-parse',
                     '--show-toplevel').decode("utf-8").strip()
    files = system('git', 'status', '--porcelain').decode("utf-8")
    files = modified.findall(files)

    print("Formatting files")
    for name in files:
        filepath = os.path.join(basedir, name)
        autopep8(filepath)
        system("git", "add", filepath)
        print(".", end="")
    print("")


if __name__ == '__main__':
    main()
