name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create database
        run: mysql -uroot -proot -e "CREATE DATABASE socks_test;"
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install necessary system packages
        run: |
          sudo apt-get install python3.6-dev libmysqlclient-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install coveralls
          pipenv install --dev
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest, report to Coveralls
        run: |
          pipenv run pytest tests --cov=.
          coveralls
        env:
          database: '{"username":"root","password":"root","server":"127.0.0.1","database":"socks_test"}'
          test_database: '{"username":"root","password":"root","server":"127.0.0.1","database":"socks_test"}'
          secret_key: secret_key123
          drop_tables: False
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
