name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_USER: sockschat
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: socks_test
          MYSQL_ROOT_PASSWORD: test
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install necessary system packages
        run: |
          sudo apt-get install python3.6-dev libmysqlclient-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pipenv run pytest tests --cov=app
        env:
          database: '{"username":"sockschat","password":"test","server":"127.0.0.1","database":"socks_test"}'
          test_database: '{"username":"sockschat","password":"test","server":"127.0.0.1","database":"socks_test"}'
          port: ${{ job.services.mariadb.ports[3306] }}
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
